[package]
name = "ruhvro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.9.0"
apache-avro = "0.16.0"
anyhow = "1.0.80"